### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by ondrejbartas** [jonleighton/focused_controller#38]
Hello,

are you planning on allowing to use focused controller with Rails 4.2?

**Comment by jonleighton** [comment]
Yes. Patches welcome.

**Comment by clemens** [comment]
I have a branch here: https://github.com/clemens/focused_controller/tree/feature/rails-4.2. It's not pretty but I think it works. Maybe try it out and if it does, I can turn it into a PR.

**Comment by jonleighton** [comment]
I've released 2.0.0 with Rails 4.2 support. Thanks @clemens for your initial work, it was useful.

**Comment by clemens** [comment]
Cool! Happy to help. :)
